### ISSUE TITLE
Runtime Application Presets

### ISSUE THREAD

**Issue by mathiasmah** [CantaraJS/cantara#59]

**Comment by scriptify** [comment]
A common need for more complex apps (frontend or backend) are configuration presets: For example different client application configurations. Instead of hard-coding them in your code and commenting them back in and out, let's make this first-class-citizen of Cantara.

**The implementation**:
Inside an application folder (a react app, node app, or serverless app), a new folder called `presets` can be created. Inside that folder, the developer can create `.json` files. If the developer wants to make use of those presets, at least one such JSON file needs to be present. If there's a file called `default.json`, that will be used as the default preset. Other presets can be arbitrarily named, e.g. `client-1.json`. It's up to the application how the JSON structure looks like, but it should be the same for each file of course.
Now, as soon as the developer starts developing the Cantara app, the current preset becomes available in the `process.env.CANTARA_APP_PRESET`. A `--preset` parameter with the filename (without the `.json` extension) can be specified to determine what preset should be loaded. If no such parameter is specified, the `default.json` file or, if no such file, the first JSON file will be used.

**Considerations:**
- We need to look if a parsed JSON object can be saved inside an environment variable. Otherwise, we could inject some code that sets it on the `global` object.
- We could auto-generate TS types for that preset object from the JSON files using https://www.npmjs.com/package/json-schema-to-typescript

RAPs ftw!

**Comment by mathiasmah** [comment]
If presets are used for the production build, it could be potentiality dangerous, if accidentally  the wrong preset is selected.
Because of this, I would omit the preset completely, if no `--preset` parameter is specified **and** no `default.json` is present.
